# Generated by Django 5.0.7 on 2024-07-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('download_link', models.URLField()),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
