# Generated by Django 5.0.7 on 2024-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('nollywood', 'Nollywood'), ('music', 'Music')], max_length=50),
        ),
    ]
