# Generated by Django 5.0.7 on 2024-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='download_link',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='content',
            name='poster_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
