# Generated by Django 5.0.7 on 2024-07-19 19:07

import movies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_content_download_link_alter_content_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='download_link',
            field=models.CharField(max_length=300, validators=[movies.validators.CustomURLValidator()]),
        ),
    ]
