# Generated by Django 5.0.7 on 2024-07-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_content_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='download_link',
            field=models.URLField(max_length=300),
        ),
    ]
