# Generated by Django 5.0.7 on 2024-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='download_link',
            field=models.URLField(max_length=1500),
        ),
    ]
