# Generated by Django 5.0.7 on 2024-07-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_content_download_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='download_link',
            new_name='permanent_download_link',
        ),
        migrations.AddField(
            model_name='content',
            name='current_download_link',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
    ]
