# Generated by Django 5.0.7 on 2024-07-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_rename_download_link_content_permanent_download_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='requires_special_headers',
            field=models.BooleanField(default=False),
        ),
    ]
