# Generated by Django 5.0.7 on 2024-07-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_content_requires_special_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_fzmovies',
            field=models.BooleanField(default=False),
        ),
    ]
