# Generated by Django 5.0.7 on 2024-07-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_content_is_fzmovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_fzmovies',
        ),
    ]
