# Generated by Django 5.0.7 on 2024-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_content_is_fzmovies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='requires_special_headers',
            new_name='requires_special_headers_1',
        ),
        migrations.AddField(
            model_name='content',
            name='requires_special_headers_2',
            field=models.BooleanField(default=False),
        ),
    ]
