# Generated by Django 5.0.7 on 2024-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_rename_requires_special_headers_content_requires_special_headers_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='requires_special_headers_1',
            field=models.BooleanField(default=True),
        ),
    ]
