# Generated by Django 5.0.7 on 2024-07-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_content_requires_special_headers_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='requires_special_headers_1',
            field=models.BooleanField(default=False),
        ),
    ]
