# Generated by Django 5.0.7 on 2024-07-29 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_content_requires_special_headers_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
