# Generated by Django 5.0.7 on 2024-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_content_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
